### ISSUE TITLE
Faculty Module JavaScript Form Validation!

### ISSUE THREAD

**Issue by YasirkhanStanekzai** [IHS-LMS/webapp#3]
**These six pages should be validate by JS form validation methods using _student module_ js code!**

- Faculty.html
- student-nighshift.html
- teacher-coordinator.html
- class-timetable.html
- exam-timetable.html
- Course.html

![image](https://user-images.githubusercontent.com/57432794/81927296-44334600-9598-11ea-9ce5-e660f06cfc72.png)

**Comment by SaeedaRasuly** [comment]
I have added the validation file for faculty only will add the other parts soon.

**Comment by SaeedaRasuly** [comment]
@NaveedAhmadHematmal Please kindly close this issue.
