### ISSUE TITLE
Hostel Module JavaScript Form Validation!

### ISSUE THREAD

**Issue by YasirkhanStanekzai** [IHS-LMS/webapp#4]
**These five pages should be validate by JS form validation methods _using student_ module JS code!**

- Hostel.html
- hostel-room.html
- hostel-registration.html
- hostel-employee.html
- hostel.attendance.html

![image](https://user-images.githubusercontent.com/57432794/81927923-4cd84c00-9599-11ea-8763-d15bffec82d1.png)

**Comment by SaeedaRasuly** [comment]
javascript validation files for hostel module already added.

**Comment by SaeedaRasuly** [comment]
@NaveedAhmadHematmal Please kindly close this issue, it's done!
